### ISSUE TITLE
Time/Date Library

### ISSUE THREAD

**Issue by EasternGamer** [Archaegeo/DualUniverseLuaIssues#33]
Simply a library to help convert the current system.getTime() value into a date and time format. 

For example, converting it into Tuesday, 12 October 2021, or 12/10/2021, or 5:32 PM, and so on.
Maybe some built-in support for an actual time as well so you can respect time zones.

**Comment by Archaegeo** [comment]
Fixed in 0.29 Athena with 
[Lua] getTime() is now deprecated, because it depends on the time zone. You can use instead :
[Lua] [float] getArkTime() : returns the current time since the arrival of the Arkship on September 30th, 2017
[Lua] [float] getUtcTime(): Return the current time since January 1st, 1970.
[Lua] [int] getUtcOffset(): Return the time offset between local timezone and UTC
