### ISSUE TITLE
Improved databank API

### ISSUE THREAD

**Issue by samdeane** [Archaegeo/DualUniverseLuaIssues#36]
A table-like interface should be supported for databanks, which works with real values, and requires no translation to/from strings or JSON.

This should include the ability to store sub-tables without first encoding them.

**Comment by NQ-Ligo** [comment]
Hello everyone!

We would like to change the databank system. There are a lot of problems with the way it is done, the most visible for you is the performance, and for us the server bandwidth load.

So we would like to rework it, but if we do, it will definitely change the way it works drastically. That's why we're looking at that kind of change as well.

**Comment by EasternGamer** [comment]
I would very much love for long-range communication, a heavily limited system in that regard. You can factor in certain effects like distance latency and limiting the number of messages sent/amount contained within the message.

I want to be able to know the location of my entire fleet of ships in a large PVP battle that spans over more than just 2 SU, and have them report their status to me. (Things like shield health, CCS status, fuel status) But communication is not perfectly synced, so it may take a bit to send it. Similar to how construct positions only update so often in space.

**Comment by Archaegeo** [comment]
Closed as covered by #35
